export const users = [
  {
    id: 1,
    image: "/images/Other_Images/random5.jpeg",
    name: "User 1",
    email: "user1@example.com",
    role: "admin",
  },
  {
    id: 2,
    image: "/images/Other_Images/random5.jpeg",
    name: "User 2",
    email: "user2@example.com",
    role: "user",
  },
  {
    id: 3,
    image: "/images/Other_Images/random5.jpeg",
    name: "User 3",
    email: "user3@example.com",
    role: "user",
  },
  {
    id: 4,
    image: "/images/Other_Images/random5.jpeg",
    name: "User 4",
    email: "user4@example.com",
    role: "user",
  },
  {
    id: 5,
    image: "/images/Other_Images/random5.jpeg",
    name: "User 5",
    email: "user5@example.com",
    role: "user",
  },
  {
    id: 6,
    image: "/images/Other_Images/random5.jpeg",
    name: "User 6",
    email: "user6@example.com",
    role: "admin",
  },
  {
    id: 7,
    image: "/images/Other_Images/random5.jpeg",
    name: "User 7",
    email: "user7@example.com",
    role: "user",
  },
  {
    id: 8,
    image: "/images/Other_Images/random5.jpeg",
    name: "User 8",
    email: "user8@example.com",
    role: "user",
  },
  {
    id: 9,
    image: "/images/Other_Images/random5.jpeg",
    name: "User 9",
    email: "user9@example.com",
    role: "user",
  },
  {
    id: 10,
    image: "/images/Other_Images/random5.jpeg",
    name: "User 10",
    email: "user10@example.com",
    role: "user",
  },
  {
    id: 11,
    image: "/images/Other_Images/random5.jpeg",
    name: "User 11",
    email: "user11@example.com",
    role: "admin",
  },
  {
    id: 12,
    image: "/images/Other_Images/random5.jpeg",
    name: "User 12",
    email: "user12@example.com",
    role: "user",
  },
  {
    id: 13,
    image: "/images/Other_Images/random5.jpeg",
    name: "User 13",
    email: "user13@example.com",
    role: "user",
  },
  {
    id: 14,
    image: "/images/Other_Images/random5.jpeg",
    name: "User 14",
    email: "user14@example.com",
    role: "user",
  },
  {
    id: 15,
    image: "/images/Other_Images/random5.jpeg",
    name: "User 15",
    email: "user15@example.com",
    role: "user",
  },
  {
    id: 16,
    image: "/images/Other_Images/random5.jpeg",
    name: "User 16",
    email: "user16@example.com",
    role: "admin",
  },
  {
    id: 17,
    image: "/images/Other_Images/random5.jpeg",
    name: "User 17",
    email: "user17@example.com",
    role: "user",
  },
  {
    id: 18,
    image: "/images/Other_Images/random5.jpeg",
    name: "User 18",
    email: "user18@example.com",
    role: "user",
  },
  {
    id: 19,
    image: "/images/Other_Images/random5.jpeg",
    name: "User 19",
    email: "user19@example.com",
    role: "user",
  },
  {
    id: 20,
    image: "/images/Other_Images/random5.jpeg",
    name: "User 20",
    email: "user20@example.com",
    role: "user",
  },
];
