export const rows = [
  {
    "user Name": "Ethan Thompson",
    "user Email": "ethan.thompson@example.com",
    "Buying Car": "Toyota Camry",
    "Payment status": "Paid",
    "Car Status": "Delivered",
  },
  {
    "user Name": "Liam Martin",
    "user Email": "liam.martin@example.com",
    "Buying Car": "Honda Civic",
    "Payment status": "Pending",
    "Car Status": "In Warehouse",
  },
  {
    "user Name": "Oliver Brown",
    "user Email": "oliver.brown@example.com",
    "Buying Car": "Ford Mustang",
    "Payment status": "Paid",
    "Car Status": "In Ongoing",
  },
  {
    "user Name": "Noah Hall",
    "user Email": "noah.hall@example.com",
    "Buying Car": "Nissan Altima",
    "Payment status": "Paid",
    "Car Status": "Delivered",
  },
  {
    "user Name": "Logan White",
    "user Email": "logan.white@example.com",
    "Buying Car": "Chevrolet Silverado",
    "Payment status": "Pending",
    "Car Status": "In Warehouse",
  },
  {
    "user Name": "Mason Lee",
    "user Email": "mason.lee@example.com",
    "Buying Car": "Hyundai Sonata",
    "Payment status": "Paid",
    "Car Status": "In Ongoing",
  },
  {
    "user Name": "Caleb Davis",
    "user Email": "caleb.davis@example.com",
    "Buying Car": "Subaru Outback",
    "Payment status": "Paid",
    "Car Status": "Delivered",
  },
  {
    "user Name": "Julian White",
    "user Email": "julian.white@example.com",
    "Buying Car": "Volkswagen Jetta",
    "Payment status": "Pending",
    "Car Status": "In Warehouse",
  },
  {
    "user Name": "Asher Martin",
    "user Email": "asher.martin@example.com",
    "Buying Car": "Mazda CX-5",
    "Payment status": "Paid",
    "Car Status": "In Ongoing",
  },
  {
    "user Name": "Landon Brown",
    "user Email": "landon.brown@example.com",
    "Buying Car": "Honda Accord",
    "Payment status": "Paid",
    "Car Status": "Delivered",
  },
  {
    "user Name": "Cameron Hall",
    "user Email": "cameron.hall@example.com",
    "Buying Car": "Toyota RAV4",
    "Payment status": "Pending",
    "Car Status": "In Warehouse",
  },
  {
    "user Name": "Beckett Lee",
    "user Email": "beckett.lee@example.com",
    "Buying Car": "Ford F-150",
    "Payment status": "Paid",
    "Car Status": "In Ongoing",
  },
  {
    "user Name": "Gunnar White",
    "user Email": "gunnar.white@example.com",
    "Buying Car": "Nissan Rogue",
    "Payment status": "Paid",
    "Car Status": "Delivered",
  },
  {
    "user Name": "Kai Martin",
    "user Email": "kai.martin@example.com",
    "Buying Car": "Chevrolet Equinox",
    "Payment status": "Pending",
    "Car Status": "In Warehouse",
  },
  {
    "user Name": "Jaxon Brown",
    "user Email": "jaxon.brown@example.com",
    "Buying Car": "Honda Pilot",
    "Payment status": "Paid",
    "Car Status": "In Ongoing",
  },
  {
    "user Name": "Crew Lee",
    "user Email": "crew.lee@example.com",
    "Buying Car": "Toyota Highlander",
    "Payment status": "Paid",
    "Car Status": "Delivered",
  },
  {
    "user Name": "Casey Hall",
    "user Email": "casey.hall@example.com",
    "Buying Car": "Ford Explorer",
    "Payment status": "Pending",
    "Car Status": "In Warehouse",
  },
  {
    "user Name": "Axel White",
    "user Email": "axel.white@example.com",
    "Buying Car": "Hyundai Santa Fe",
    "Payment status": "Paid",
    "Car Status": "In Ongoing",
  },
  {
    "user Name": "Jace Martin",
    "user Email": "jace.martin@example.com",
    "Buying Car": "Subaru Ascent",
    "Payment status": "Paid",
    "Car Status": "Delivered",
  },
  {
    "user Name": "Kolton Brown",
    "user Email": "kolton.brown@example.com",
    "Buying Car": "Volkswagen Atlas",
    "Payment status": "Pending",
    "Car Status": "In Warehouse",
  },
  {
    "user Name": "Brayden Lee",
    "user Email": "brayden.lee@example.com",
    "Buying Car": "Mazda CX-9",
    "Payment status": "Paid",
    "Car Status": "In Ongoing",
  },
];
