export const rows = [
  { id: 1, name: "Alice Johnson", email: "alice@example.com", role: "Admin" },
  { id: 2, name: "Bob Smith", email: "bob@example.com", role: "User" },
  { id: 3, name: "Charlie Davis", email: "charlie@example.com", role: "User" },
  { id: 4, name: "Diana King", email: "diana@example.com", role: "User" },
  { id: 5, name: "Evan White", email: "evan@example.com", role: "Admin" },
  { id: 6, name: "Alice Johnson", email: "alice@example.com", role: "Admin" },
  { id: 7, name: "Bob Smith", email: "bob@example.com", role: "User" },
  { id: 8, name: "Charlie Davis", email: "charlie@example.com", role: "User" },
  { id: 9, name: "Diana King", email: "diana@example.com", role: "User" },
  { id: 10, name: "Evan White", email: "evan@example.com", role: "Admin" },
  { id: 11, name: "Alice Johnson", email: "alice@example.com", role: "Admin" },
  { id: 12, name: "Bob Smith", email: "bob@example.com", role: "User" },
  { id: 13, name: "Charlie Davis", email: "charlie@example.com", role: "User" },
  { id: 14, name: "Diana King", email: "diana@example.com", role: "User" },
  { id: 15, name: "Evan White", email: "evan@example.com", role: "Admin" },
  { id: 16, name: "Alice Johnson", email: "alice@example.com", role: "Admin" },
  { id: 17, name: "Bob Smith", email: "bob@example.com", role: "User" },
  { id: 18, name: "Charlie Davis", email: "charlie@example.com", role: "User" },
  { id: 19, name: "Diana King", email: "diana@example.com", role: "User" },
  { id: 20, name: "Evan White", email: "evan@example.com", role: "Admin" },
];